target_fps = 60

[sim]
# This is 16:9 aspect ratio.
width = 192.0
height = 108.0


[sharks]
count = 1
linear_damping = 1.5
angular_damping = 1.0
max_force = 120.0
max_reverse_force = -40.0
max_torque = 50.0
