target_fps = 60

[sim]
# This is 16:9 aspect ratio.
width = 192.0
height = 108.0
sims_per_frame = 1


[shark]
vision_rays = 64
vision_dist = 100.0
vision_angle = 100.0
linear_damping = 1.5
angular_damping = 1.0
max_force = 120.0
max_reverse_force = -40.0
max_torque = 50.0

[fish]
count = 50
# goal for the first is to be slower with higher acceleration.
# Also, want to promote schooling somehow.
linear_damping = 2.0
angular_damping = 1.5
max_force = 40.0
max_reverse_force = -30.0
max_torque = 20.0
mutation_factor = 0.1

[dqn]
hidden_size = 32
replay_buffer_size = 1000000
train_freq = 512
batch_size = 128
gamma = 0.999
tau = 0.005
learning_rate = 0.001
eps_decay = 1000000.0
reset_delay = 100000
