target_fps = 60

[sim]
# This is 16:9 aspect ratio.
width = 192.0
height = 108.0
sims_per_frame = 1


[shark]
vision_rays = 32
vision_dist = 30.0
vision_angle = 100.0
linear_damping = 1.5
angular_damping = 1.0
max_force = 120.0
max_reverse_force = -40.0
max_torque = 50.0

[fish]
count = 50
# goal for the first is to be slower with higher acceleration.
# Also, want to promote schooling somehow.
linear_damping = 2.0
angular_damping = 1.5
max_force = 40.0
max_reverse_force = -30.0
max_torque = 20.0
mutation_factor = 0.1
